name: mask
base: core20
version: '0.1'
summary: The binary masking tool
description: |
  This tool provides basic binary operation like XOR and HEX on string
  or stdin inputs. Nothing special, just wanted to write a snap.

grade: devel
confinement: devmode

apps:
  mask:
    command: usr/bin/mask

parts:
  cmake-build:
    plugin: cmake
    cmake-parameters:
            - -DCMAKE_INSTALL_PREFIX=/usr
    source: .
    build-packages:
            - g++
